from __future__ import annotations

import argparse
import re
from datetime import date, timedelta
from pathlib import Path
from typing import Any

import yaml

from agentctl.files import DataFileError, load_data
from agentctl.risk import TIER_RANK
from agentctl.scaffold import _add_if_missing, _write_files
from agentctl.ui import status, step, success

NAME_PATTERN = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
PACKAGE_PATTERN = re.compile(r"^[a-z_][a-z0-9_]*$")


def scaffold_system(args: argparse.Namespace) -> int:
    if not NAME_PATTERN.fullmatch(args.name):
        raise ValueError("system name must be lowercase hyphenated text")
    if not PACKAGE_PATTERN.fullmatch(args.package):
        raise ValueError("package must be a valid lowercase Python package name")
    if len(args.member) < 2:
        raise ValueError(
            "system scaffold requires at least two --member AGENT:ROLE values"
        )

    root = args.root.resolve()
    members = _resolve_members(root, args.member)
    if len({item["agent"] for item in members}) != len(members):
        raise ValueError("system members must be unique")
    maximum_member_tier = max(
        (item["risk_tier"] for item in members), key=TIER_RANK.__getitem__
    )
    if TIER_RANK[args.risk_tier] < TIER_RANK[maximum_member_tier]:
        raise ValueError(
            f"system risk tier {args.risk_tier} is below member floor {maximum_member_tier}"
        )

    module_name = args.name.replace("-", "_")
    system_dir = root / "src" / args.package / "systems" / module_name
    temporal = args.execution_class != "ephemeral" or args.with_temporal
    spec = _system_spec(args, members, module_name, temporal)

    files: dict[Path, str] = {
        system_dir
        / "__init__.py": '"""Multi-agent system package generated by agentctl."""\n',
        system_dir / "system.yaml": yaml.safe_dump(spec, sort_keys=False),
        system_dir / "factory.py": _factory(),
        system_dir / "models.py": _models(),
        system_dir / "coordination.py": _coordination(),
        system_dir / "policies" / "delegation.yaml": _delegation_policy(spec),
        system_dir / "policies" / "data-flow.yaml": _data_flow_policy(),
        system_dir / "policies" / "termination.yaml": _termination_policy(spec),
        root
        / "docs"
        / "risk-assessments"
        / "systems"
        / f"{args.name}.yaml": _risk_assessment(args, members, maximum_member_tier),
        root / "docs" / "threat-models" / f"{args.name}.md": _threat_model(args.name),
    }
    files.update(_eval_files(root, args.name, module_name))
    _add_if_missing(files, root / "src" / args.package / "__init__.py", "")
    _add_if_missing(files, root / "src" / args.package / "systems" / "__init__.py", "")

    if temporal:
        files.update(_temporal_files(root, args.package, module_name))
    if args.execution_class == "human_governed":
        files[
            root / "src" / args.package / "policy" / "approvals" / f"{module_name}.yaml"
        ] = _approval_policy()
    if args.dynamic_membership:
        files[system_dir / "policies" / "registry.yaml"] = _registry_policy()
        files[system_dir / "policies" / "admission.yaml"] = _admission_policy()

    with status("Creating the golden-path multi-agent system package…"):
        _write_files(files, force=args.force)
    success(
        "Multi-agent system scaffold created",
        (
            ("System", args.name),
            ("Topology", args.topology),
            ("Members", str(len(members))),
            ("Execution", args.execution_class),
            ("Risk", args.risk_tier),
            ("Files", str(len(files))),
            ("Root", str(root)),
        ),
    )
    step(f"Next: agentctl system validate --root {root}")
    step(f"Then: agentctl eval run {args.name} --system --root {root}")
    return 0


def _resolve_members(root: Path, values: list[str]) -> list[dict[str, Any]]:
    resolved: list[dict[str, Any]] = []
    for value in values:
        agent, separator, role = value.partition(":")
        if (
            not separator
            or not NAME_PATTERN.fullmatch(agent)
            or not NAME_PATTERN.fullmatch(role)
        ):
            raise ValueError(f"invalid member {value!r}; expected lowercase AGENT:ROLE")
        matches: list[tuple[Path, dict[str, Any]]] = []
        for path in root.glob("src/*/agents/*/agent.yaml"):
            try:
                spec = load_data(path)
            except DataFileError:
                continue
            if spec.get("name") == agent:
                matches.append((path, spec))
        if not matches:
            raise ValueError(f"member agent {agent!r} was not found under src/*/agents")
        if len(matches) > 1:
            raise ValueError(f"member agent {agent!r} is ambiguous")
        _, spec = matches[0]
        metadata = spec.get("metadata")
        if not isinstance(metadata, dict):
            raise TypeError(f"member agent {agent!r} has invalid metadata")
        resolved.append(
            {
                "agent": agent,
                "role": role,
                "version": metadata.get("version"),
                "execution_class": metadata.get("execution_class"),
                "risk_tier": metadata.get("risk_tier"),
                "risk_assessment": metadata.get("risk_assessment"),
            }
        )
    return resolved


def _system_spec(
    args: argparse.Namespace,
    members: list[dict[str, Any]],
    module_name: str,
    temporal: bool,
) -> dict[str, Any]:
    coordinator = members[0]["agent"]
    interactions = [
        {
            "id": f"delegate-{member['agent']}",
            "from": coordinator,
            "to": member["agent"],
            "mode": "delegate",
            "input_schema": "DelegationRequest",
            "output_schema": "DelegationResult",
            "policy": f"policies/delegation.yaml#delegate-{member['agent']}",
            "max_calls": 2,
            "timeout_seconds": 60,
        }
        for member in members[1:]
    ]
    topology: dict[str, Any] = {
        "type": args.topology,
        "orchestrator": f"{args.name}-workflow",
        "coordinator": coordinator,
        "dynamic_membership": args.dynamic_membership,
        "recursive_delegation": args.recursive_delegation,
    }
    if args.dynamic_membership:
        topology.update(
            {
                "registry": "policies/registry.yaml",
                "admission_policy": "policies/admission.yaml",
            }
        )
    metadata: dict[str, Any] = {
        "contract_version": 1,
        "owner": args.owner,
        "operational_owner": args.operational_owner,
        "version": "0.1.0",
        "execution_class": args.execution_class,
        "governance_tier": args.risk_tier,
        "risk_assessment": f"docs/risk-assessments/systems/{args.name}.yaml",
        "threat_model": f"docs/threat-models/{args.name}.md",
        "evaluation_policy": f"evals/systems/{module_name}/release-policy.yaml",
        "data_classification": "internal",
        "temporal_enabled": temporal,
    }
    if args.execution_class == "human_governed":
        metadata["approval_policy"] = (
            f"src/{args.package}/policy/approvals/{module_name}.yaml"
        )
    return {
        "name": args.name,
        "description": "Replace with the multi-agent system's bounded purpose.",
        "metadata": metadata,
        "justification": {
            "decision_owner": args.owner,
            "review_by": (date.today() + timedelta(days=180)).isoformat(),
            "claimed_benefits": [
                "Replace with a testable benefit over a simpler baseline."
            ],
            "baseline": "replace-with-single-agent-or-deterministic-baseline",
            "evidence": f"artifacts/evals/{args.name}/admission.json",
            "success_measures": ["replace-with-measurable-success-criterion"],
        },
        "topology": topology,
        "members": [
            {
                "agent": item["agent"],
                "version": item["version"],
                "role": item["role"],
                "required": True,
                "restrictions": {
                    "skills": {"include": []},
                    "toolsets": {"include": []},
                    "authorization_scopes_max": [],
                    "data_classification_max": "internal",
                },
            }
            for item in members
        ],
        "interactions": interactions,
        "limits": {
            "max_agent_runs": max(4, len(members) * 2),
            "max_delegation_depth": 2 if args.recursive_delegation else 1,
            "max_parallel_agents": len(members),
            "max_rounds": 3,
            "max_model_requests": max(12, len(members) * 4),
            "max_tool_calls": max(16, len(members) * 6),
            "max_input_tokens": 80000,
            "max_output_tokens": 12000,
            "max_cost_usd": 2.0,
            "deadline_seconds": 180,
        },
        "state": {
            "owner": f"{args.name}-workflow",
            "shared_memory": "none",
            "artifact_policy": "policies/data-flow.yaml",
        },
        "termination": {
            "policy": "policies/termination.yaml",
            "success_states": ["completed"],
            "escalation_state": "escalated-to-human",
        },
    }


def _factory() -> str:
    return '''"""Validated assembly for the multi-agent system."""


def build_system(settings):
    """Resolve pinned members, policies, graph, budgets, and manifest."""
    spec = settings.load_system_spec(__package__)
    members = settings.agent_registry.resolve_members(spec.members)
    policies = settings.policy_registry.resolve_system_policies(spec)
    graph = settings.graph_factory.build(spec.interactions)
    settings.validate_system_contract(spec, members, graph, policies)
    manifest = settings.manifest_factory.build(spec, members, graph, policies)
    return settings.system_runtime(spec, members, graph, policies, manifest)
'''


def _models() -> str:
    return """from typing import Any, Literal

from pydantic import BaseModel, Field


class DelegationRequest(BaseModel):
    delegation_id: str
    objective: str
    input: dict[str, Any]
    depth: int = Field(ge=0)


class DelegationResult(BaseModel):
    delegation_id: str
    status: Literal["completed", "needs_information", "escalated", "failed"]
    output: dict[str, Any] | None = None
    evidence_refs: list[str] = []
"""


def _coordination() -> str:
    return '''"""Deterministic graph, authorization, budget, and termination policy."""

# Keep policy decisions typed and deterministic. Agent output proposes work;
# this module validates membership, edge, authority, data, budget, and state
# before the workflow dispatches it.
'''


def _delegation_policy(spec: dict[str, Any]) -> str:
    interactions = {
        item["id"]: {
            "callers": [item["from"]],
            "callees": [item["to"]],
            "mode": item["mode"],
            "authorization_scopes_max": [],
            "data_classification_max": "internal",
            "budget": {
                "max_model_requests": 3,
                "max_tool_calls": 5,
                "max_input_tokens": 20000,
                "max_output_tokens": 3000,
                "max_cost_usd": 0.5,
            },
            "retry": {
                "maximum_attempts": 2,
                "retryable_failures": ["transient_provider", "transient_dependency"],
                "non_retryable_failures": [
                    "invalid_input",
                    "authorization_denied",
                    "policy_blocked",
                    "budget_exhausted",
                ],
            },
            "failure": {"required": True, "on_failure": "escalate"},
        }
        for item in spec["interactions"]
    }
    return yaml.safe_dump(
        {
            "schema_version": 1,
            "defaults": {
                "recursive_delegation": spec["topology"]["recursive_delegation"],
                "share_parent_history": False,
                "forward_credentials": False,
                "require_tenant_binding": True,
                "reserve_budget_before_dispatch": True,
            },
            "interactions": interactions,
        },
        sort_keys=False,
    )


def _data_flow_policy() -> str:
    return """schema_version: 1
history:
  share_parent_history: false
  permit_task_summary: true
  permit_evidence_references: true
  include_hidden_instructions: false
  include_credentials: false
artifact_store:
  authorization_required: true
  integrity_hash_required: true
  uri_is_not_authorization: true
"""


def _termination_policy(spec: dict[str, Any]) -> str:
    return yaml.safe_dump(
        {
            "schema_version": 1,
            "limits": spec["limits"],
            "terminal_states": {
                "success": spec["termination"]["success_states"],
                "escalation": [spec["termination"]["escalation_state"]],
                "failure": ["failed-permanent", "partial-effect"],
            },
            "result_handling": {
                "late_result": "discard_and_audit",
                "duplicate_result": "deduplicate_by_delegation_id",
                "malformed_result": "reject_and_apply_failure_policy",
                "conflicting_result": "preserve_dissent_and_escalate",
            },
        },
        sort_keys=False,
    )


def _risk_assessment(
    args: argparse.Namespace,
    members: list[dict[str, Any]],
    maximum_member_tier: str,
) -> str:
    impact, likelihood = {
        "low": (1, 1),
        "medium": (2, 2),
        "high": (2, 4),
        "critical": (3, 4),
    }[args.risk_tier]
    assessed_at = date.today()
    review_days = {"low": 365, "medium": 180, "high": 90, "critical": 30}
    review_by = assessed_at + timedelta(days=review_days[args.risk_tier])
    decision = "no_go" if args.risk_tier == "critical" else "conditional_go"
    payload = {
        "schema_version": 1,
        "assessment": {
            "system": args.name,
            "system_version": "0.1.0",
            "composition_manifest": "replace-with-approved-manifest-id",
            "assessment_version": "0.1.0",
            "status": "draft",
            "assessed_at": assessed_at.isoformat(),
            "review_by": review_by.isoformat(),
            "prepared_by": args.owner,
            "approved_by": [],
        },
        "scope": {
            "intended_use": "Replace with the system's bounded intended use.",
            "prohibited_uses": ["Operate outside the reviewed graph or authority."],
            "users": ["replace-with-intended-users"],
            "affected_parties": ["replace-with-affected-parties"],
            "environments": ["development"],
            "jurisdictions": ["replace-with-jurisdictions"],
            "execution_class": args.execution_class,
            "topology": {
                "profile": args.topology,
                "dynamic_membership": args.dynamic_membership,
                "recursive_delegation": args.recursive_delegation,
                "maximum_members": len(members),
            },
        },
        "member_assessments": [
            {
                "agent": item["agent"],
                "agent_version": item["version"],
                "governance_tier": item["risk_tier"],
                "assessment": item["risk_assessment"],
                "assessment_digest": "replace-with-sha256",
                "status": "draft",
            }
            for item in members
        ],
        "regulatory_screen": {
            "prohibited_use": False,
            "applicable_regimes": [],
            "required_reviews": [],
            "governance_floors": [],
            "notes": "Complete applicability review before approval.",
        },
        "classification": {
            "governance_tier": args.risk_tier,
            "maximum_member_tier": maximum_member_tier,
            "maximum_inherent_tier": args.risk_tier,
            "maximum_residual_tier": args.risk_tier,
            "decision": decision,
            "rationale": "Draft classification generated from selected tier.",
        },
        "scenarios": [
            {
                "id": "SYS-RISK-COORD-001",
                "title": "Incorrect or incomplete coordinated outcome",
                "status": "open",
                "family": "coordination_and_emergent_behavior",
                "statement": (
                    "Because routing, member, or aggregation behavior may fail, the "
                    "system could produce an incorrect or incomplete outcome, causing "
                    "harm to affected users or dependent operations."
                ),
                "primary_dimension": "operational",
                "secondary_dimensions": [],
                "affected_parties": ["replace-with-affected-parties"],
                "affected_assets": ["replace-with-affected-assets"],
                "participating_roles": [item["role"] for item in members],
                "interactions": [f"delegate-{item['agent']}" for item in members[1:]],
                "referenced_member_scenarios": [],
                "causes": ["routing error", "member failure", "aggregation error"],
                "preconditions": ["The system receives a request within scope."],
                "consequences": ["A dependent process receives an incorrect outcome."],
                "inherent": {
                    "impact": impact,
                    "likelihood": likelihood,
                    "tier": args.risk_tier,
                    "confidence": "low",
                    "rationale": "Replace with evidence-based inherent rationale.",
                },
                "controls": [],
                "residual": {
                    "impact": impact,
                    "likelihood": likelihood,
                    "tier": args.risk_tier,
                    "confidence": "low",
                    "rationale": "No reduction credited until controls are verified.",
                },
                "treatment": "mitigate",
                "owner": args.owner,
                "eval_cases": ["SYS-RISK-COORD-001"],
                "indicators": ["system_failure_count"],
                "alerts": ["material system failure detected"],
                "runbook": f"docs/runbooks/{args.name}.md",
                "acceptance": None,
            }
        ],
        "acceptance": {
            "accepted_scenarios": [],
            "conditions": [],
            "accountable_role": "replace-with-risk-authority",
            "accepted_by": None,
            "accepted_at": None,
            "expires_at": None,
        },
        "monitoring": {
            "indicators": ["system_failure_count", "system_cost_per_success"],
            "review_cadence_days": review_days[args.risk_tier],
            "next_review_at": review_by.isoformat(),
        },
        "open_questions": ["Complete the system assessment and attach evidence."],
    }
    return yaml.safe_dump(payload, sort_keys=False)


def _threat_model(name: str) -> str:
    return f"""# Threat model: {name}

## Scope and graph

Document members, roles, interactions, state, registries, data, and effects.

## Trust boundaries

Document users, orchestrator, each member, transports, stores, tools, approvals,
telemetry, and operators.

## Threats and controls

Cover injection propagation, authority laundering, confused deputy, poisoning,
false consensus, dynamic admission, resource exhaustion, and duplicate effects.
"""


def _eval_files(root: Path, name: str, module_name: str) -> dict[Path, str]:
    directory = root / "evals" / "systems" / module_name
    report = f"artifacts/evals/{name}.json"
    return {
        directory / "README.md": (
            f"# {name} system evaluations\n\n"
            "Replace the generated adapter with member, interaction, coordination, "
            "durability, adversarial, and end-to-end evaluations.\n"
        ),
        directory / "run.py": f'''import json
import os
from pathlib import Path

report = {{
    "schema_version": 1,
    "subject": {{"kind": "system", "name": os.environ["AGENTCTL_SUBJECT_NAME"]}},
    "hard_gates": {{"placeholder_eval_removed": False}},
    "metrics": {{"task_success_rate": 0.0}},
}}
Path(os.environ.get("AGENTCTL_REPORT_PATH", "{report}")).write_text(
    json.dumps(report, indent=2), encoding="utf-8"
)
''',
        directory / "release-policy.yaml": """schema_version: 1
hard_gates:
  placeholder_eval_removed: true
thresholds:
  task_success_rate: {min: 0.90}
required_provenance:
  - git_commit
""",
        directory / "datasets" / "smoke" / ".gitkeep": "",
        directory / "datasets" / "routing" / ".gitkeep": "",
        directory / "datasets" / "adversarial" / ".gitkeep": "",
        directory / "datasets" / "durability" / ".gitkeep": "",
        directory / "baselines" / ".gitkeep": "",
    }


def _temporal_files(root: Path, package: str, module_name: str) -> dict[Path, str]:
    workflows = root / "src" / package / "workflows"
    activities = root / "src" / package / "activities"
    files = {
        workflows / f"{module_name}.py": '''"""Deterministic system coordination."""

# Own typed state, graph versions, budgets, routing validation, aggregation,
# termination, approval, cancellation, and compensation here.
''',
        activities / f"{module_name}.py": '''"""Nondeterministic system activities."""

# Run member agents, registries, tools, artifact stores, and other I/O here.
''',
    }
    _add_if_missing(files, workflows / "__init__.py", "")
    _add_if_missing(files, activities / "__init__.py", "")
    return files


def _approval_policy() -> str:
    return """required: true
bind_to_action_hash: true
bind_to_manifest_id: true
bind_to_actor_and_tenant: true
authenticated_actor: true
expires_after_seconds: 86400
audit_required: true
"""


def _registry_policy() -> str:
    return """schema_version: 1
authenticated_registry: true
immutable_versions: true
integrity_metadata_required: true
allowlisted_publishers: []
deny_quarantined: true
"""


def _admission_policy() -> str:
    return """schema_version: 1
require_agent_conformance: true
require_compatible_schemas: true
require_current_risk_assessment: true
require_owner: true
record_run_manifest: true
maximum_dynamic_members: 4
"""
